[package]
name = "xxc-aptd-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
askama.workspace = true
axum.workspace = true
futures-util.workspace = true
httpdate.workspace = true
http-body.workspace = true
ipnet.workspace = true
percent-encoding.workspace = true
pulldown-cmark.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_urlencoded.workspace = true
tempfile.workspace = true
tokio.workspace = true
tower.workspace = true
tower-http.workspace = true
tracing.workspace = true
uuid.workspace = true
xxc-aptd-core.workspace = true
zeroize.workspace = true

[dev-dependencies]
tempfile.workspace = true
